-- TwinkleGo Supabase schema, RLS policies, and workflow functions.
-- Run this in the Supabase SQL editor for project qtgvfnlageqhhtrpxkrw.

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text unique not null,
  interest text not null default 'help',
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  phone text,
  address text,
  role text not null default 'customer' check (role in ('customer', 'runner', 'both')),
  avatar_url text,
  is_verified boolean not null default false,
  phone_verified boolean not null default false,
  address_verified boolean not null default false,
  rating numeric(2,1) default 0,
  rating_count int default 0,
  lat numeric(10,7),
  lng numeric(10,7),
  is_available boolean not null default false,
  emergency_contact_name text,
  emergency_contact_phone text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists phone_verified boolean not null default false;
alter table public.profiles add column if not exists address_verified boolean not null default false;

create table if not exists public.verifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  id_type text not null,
  id_number text not null,
  id_image_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewer_notes text,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.errands (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  description text,
  category text not null default 'errand' check (category in ('groceries', 'delivery', 'home_help', 'errand', 'temporary_job', 'service_request')),
  pickup_lat numeric(10,7),
  pickup_lng numeric(10,7),
  dropoff_lat numeric(10,7),
  dropoff_lng numeric(10,7),
  pickup_address text,
  dropoff_address text,
  status text not null default 'posted' check (status in ('posted', 'accepted', 'in_progress', 'completed', 'cancelled', 'disputed')),
  price numeric(10,2) not null default 0,
  distance_km numeric(8,2),
  assigned_runner_id uuid references public.profiles(id),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1 from information_schema.table_constraints
    where constraint_schema = 'public'
      and table_name = 'errands'
      and constraint_name = 'errands_category_check'
  ) then
    alter table public.errands drop constraint errands_category_check;
  end if;

  alter table public.errands
    add constraint errands_category_check
    check (category in ('groceries', 'delivery', 'home_help', 'errand', 'temporary_job', 'service_request'));
end $$;

create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade unique not null,
  balance numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  wallet_id bigint references public.wallets(id) on delete cascade not null,
  type text not null check (type in ('deposit', 'withdrawal', 'payment', 'earning', 'refund')),
  amount numeric(12,2) not null,
  description text,
  related_errand_id bigint references public.errands(id),
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  errand_id bigint references public.errands(id) on delete cascade not null,
  reviewer_id uuid references public.profiles(id) on delete cascade not null,
  reviewee_id uuid references public.profiles(id) on delete cascade not null,
  rating int not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique(errand_id, reviewer_id)
);

create table if not exists public.disputes (
  id bigint generated by default as identity primary key,
  errand_id bigint references public.errands(id) on delete cascade not null,
  raised_by uuid references public.profiles(id) on delete cascade not null,
  reason text not null,
  category text not null default 'other' check (category in ('service_issue', 'no_show', 'safety_concern', 'other')),
  status text not null default 'open' check (status in ('open', 'investigating', 'resolved')),
  resolution text,
  resolved_by uuid references public.profiles(id),
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.gps_records (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  lat numeric(10,7) not null,
  lng numeric(10,7) not null,
  recorded_at timestamptz not null default now()
);

create table if not exists public.task_tracking (
  id bigint generated by default as identity primary key,
  errand_id bigint references public.errands(id) on delete cascade unique not null,
  phase text not null default 'accepted' check (phase in ('accepted', 'heading_to_pickup', 'picked_up', 'en_route_delivery', 'delivered')),
  runner_lat numeric(10,7),
  runner_lng numeric(10,7),
  distance_to_next_km numeric(8,2),
  eta_minutes int,
  accepted_at timestamptz,
  heading_to_pickup_at timestamptz,
  picked_up_at timestamptz,
  en_route_delivery_at timestamptz,
  delivered_at timestamptz,
  last_location_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  body text,
  is_read boolean not null default false,
  related_errand_id bigint references public.errands(id),
  created_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;
alter table public.profiles enable row level security;
alter table public.verifications enable row level security;
alter table public.errands enable row level security;
alter table public.wallets enable row level security;
alter table public.transactions enable row level security;
alter table public.reviews enable row level security;
alter table public.disputes enable row level security;
alter table public.gps_records enable row level security;
alter table public.task_tracking enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "Anyone can join waitlist" on public.waitlist;
drop policy if exists "Public profiles are viewable by everyone" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Admins can update profiles" on public.profiles;
drop policy if exists "Users can view own verifications" on public.verifications;
drop policy if exists "Users can submit own verifications" on public.verifications;
drop policy if exists "Admins can manage verifications" on public.verifications;
drop policy if exists "Users can view relevant errands" on public.errands;
drop policy if exists "Verified users can create errands" on public.errands;
drop policy if exists "Users can create errands" on public.errands;
drop policy if exists "Errand parties can update" on public.errands;
drop policy if exists "Verified runners can accept posted errands" on public.errands;
drop policy if exists "Admins can view all errands" on public.errands;
drop policy if exists "Users can view own wallet" on public.wallets;
drop policy if exists "Admins can view wallets" on public.wallets;
drop policy if exists "Users can view own transactions" on public.transactions;
drop policy if exists "Admins can view transactions" on public.transactions;
drop policy if exists "Reviews are viewable by everyone" on public.reviews;
drop policy if exists "Users can create reviews" on public.reviews;
drop policy if exists "Dispute parties can view" on public.disputes;
drop policy if exists "Users can raise disputes" on public.disputes;
drop policy if exists "Admins can manage disputes" on public.disputes;
drop policy if exists "Users can view own GPS" on public.gps_records;
drop policy if exists "Users can insert own GPS" on public.gps_records;
drop policy if exists "Admins can view GPS records" on public.gps_records;
drop policy if exists "Task parties can view tracking" on public.task_tracking;
drop policy if exists "Assigned runners can create tracking" on public.task_tracking;
drop policy if exists "Assigned runners can update tracking" on public.task_tracking;
drop policy if exists "Admins can manage tracking" on public.task_tracking;
drop policy if exists "Users can view own notifications" on public.notifications;
drop policy if exists "Users can update own notifications" on public.notifications;
drop policy if exists "Authenticated users can create notifications" on public.notifications;

create policy "Anyone can join waitlist" on public.waitlist
  for insert with check (true);

create policy "Public profiles are viewable by everyone" on public.profiles
  for select using (true);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Admins can update profiles" on public.profiles
  for update using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

create policy "Users can view own verifications" on public.verifications
  for select using (auth.uid() = user_id);

create policy "Users can submit own verifications" on public.verifications
  for insert with check (auth.uid() = user_id);

create policy "Admins can manage verifications" on public.verifications
  for all using (exists (select 1 from public.profiles where id = auth.uid() and is_admin))
  with check (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

create policy "Users can view relevant errands" on public.errands
  for select using (
    auth.uid() = customer_id
    or auth.uid() = assigned_runner_id
    or status = 'posted'
    or exists (select 1 from public.profiles where id = auth.uid() and is_admin)
  );

create policy "Verified users can create errands" on public.errands
  for insert with check (
    auth.uid() = customer_id
    and exists (select 1 from public.profiles where id = auth.uid() and is_verified)
  );

create policy "Errand parties can update" on public.errands
  for update using (auth.uid() = customer_id or auth.uid() = assigned_runner_id)
  with check (auth.uid() = customer_id or auth.uid() = assigned_runner_id);

create policy "Verified runners can accept posted errands" on public.errands
  for update using (
    status = 'posted'
    and assigned_runner_id is null
    and auth.uid() <> customer_id
    and exists (
      select 1 from public.profiles
      where id = auth.uid()
      and is_verified
      and role in ('runner', 'both')
    )
  )
  with check (
    status = 'accepted'
    and assigned_runner_id = auth.uid()
  );

create policy "Admins can view all errands" on public.errands
  for all using (exists (select 1 from public.profiles where id = auth.uid() and is_admin))
  with check (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

create policy "Users can view own wallet" on public.wallets
  for select using (auth.uid() = user_id);

create policy "Admins can view wallets" on public.wallets
  for select using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

create policy "Users can view own transactions" on public.transactions
  for select using (
    exists (select 1 from public.wallets where id = wallet_id and user_id = auth.uid())
  );

create policy "Admins can view transactions" on public.transactions
  for select using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

create policy "Reviews are viewable by everyone" on public.reviews
  for select using (true);

create policy "Users can create reviews" on public.reviews
  for insert with check (
    auth.uid() = reviewer_id
    and exists (
      select 1 from public.errands e
      where e.id = errand_id
      and e.status = 'completed'
      and (e.customer_id = auth.uid() or e.assigned_runner_id = auth.uid())
      and (e.customer_id = reviewee_id or e.assigned_runner_id = reviewee_id)
      and reviewee_id <> auth.uid()
    )
  );

create policy "Dispute parties can view" on public.disputes
  for select using (
    auth.uid() = raised_by
    or exists (select 1 from public.errands where id = errand_id and (customer_id = auth.uid() or assigned_runner_id = auth.uid()))
    or exists (select 1 from public.profiles where id = auth.uid() and is_admin)
  );

create policy "Users can raise disputes" on public.disputes
  for insert with check (
    auth.uid() = raised_by
    and exists (select 1 from public.errands where id = errand_id and (customer_id = auth.uid() or assigned_runner_id = auth.uid()))
  );

create policy "Admins can manage disputes" on public.disputes
  for all using (exists (select 1 from public.profiles where id = auth.uid() and is_admin))
  with check (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

create policy "Users can view own GPS" on public.gps_records
  for select using (auth.uid() = user_id);

create policy "Users can insert own GPS" on public.gps_records
  for insert with check (auth.uid() = user_id);

create policy "Admins can view GPS records" on public.gps_records
  for select using (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

create policy "Task parties can view tracking" on public.task_tracking
  for select using (
    exists (
      select 1 from public.errands
      where id = errand_id
      and (customer_id = auth.uid() or assigned_runner_id = auth.uid())
    )
    or exists (select 1 from public.profiles where id = auth.uid() and is_admin)
  );

create policy "Assigned runners can create tracking" on public.task_tracking
  for insert with check (
    exists (
      select 1 from public.errands
      where id = errand_id
      and assigned_runner_id = auth.uid()
      and status in ('accepted', 'in_progress')
    )
  );

create policy "Assigned runners can update tracking" on public.task_tracking
  for update using (
    exists (
      select 1 from public.errands
      where id = errand_id
      and assigned_runner_id = auth.uid()
      and status in ('accepted', 'in_progress')
    )
  )
  with check (
    exists (
      select 1 from public.errands
      where id = errand_id
      and assigned_runner_id = auth.uid()
      and status in ('accepted', 'in_progress')
    )
  );

create policy "Admins can manage tracking" on public.task_tracking
  for all using (exists (select 1 from public.profiles where id = auth.uid() and is_admin))
  with check (exists (select 1 from public.profiles where id = auth.uid() and is_admin));

create policy "Users can view own notifications" on public.notifications
  for select using (auth.uid() = user_id);

create policy "Users can update own notifications" on public.notifications
  for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Authenticated users can create notifications" on public.notifications
  for insert with check (auth.uid() is not null);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'avatar_url', null),
    coalesce(new.raw_user_meta_data->>'role', 'customer')
  )
  on conflict (id) do nothing;

  insert into public.wallets (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.update_user_rating()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set
    rating = (select coalesce(round(avg(rating)::numeric, 1), 0) from public.reviews where reviewee_id = new.reviewee_id),
    rating_count = (select count(*) from public.reviews where reviewee_id = new.reviewee_id),
    updated_at = now()
  where id = new.reviewee_id;
  return new;
end;
$$;

drop trigger if exists on_review_created on public.reviews;
create trigger on_review_created
  after insert on public.reviews
  for each row execute procedure public.update_user_rating();

create or replace function public.adjust_wallet_balance(
  transaction_type text,
  transaction_amount numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  user_wallet public.wallets%rowtype;
  signed_amount numeric;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if transaction_type not in ('deposit', 'withdrawal') or transaction_amount <= 0 then
    raise exception 'Invalid wallet transaction';
  end if;

  select * into user_wallet from public.wallets where user_id = current_user_id for update;
  if not found then
    insert into public.wallets (user_id) values (current_user_id)
    returning * into user_wallet;
  end if;

  signed_amount := case when transaction_type = 'withdrawal' then -transaction_amount else transaction_amount end;

  if transaction_type = 'withdrawal' and user_wallet.balance < transaction_amount then
    raise exception 'Insufficient wallet balance';
  end if;

  update public.wallets
  set balance = balance + signed_amount
  where id = user_wallet.id;

  insert into public.transactions (wallet_id, type, amount, description)
  values (
    user_wallet.id,
    transaction_type,
    signed_amount,
    case when transaction_type = 'deposit' then 'Manual wallet top-up' else 'Manual withdrawal request' end
  );
end;
$$;

create or replace function public.complete_errand(target_errand_id bigint)
returns public.errands
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  target public.errands%rowtype;
  customer_wallet public.wallets%rowtype;
  runner_wallet public.wallets%rowtype;
  task_price numeric;
begin
  if current_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select * into target
  from public.errands
  where id = target_errand_id
  for update;

  if not found then
    raise exception 'Errand not found';
  end if;

  if target.assigned_runner_id is distinct from current_user_id then
    raise exception 'Only the assigned runner can complete this errand';
  end if;

  if target.status <> 'in_progress' then
    raise exception 'Errand must be in progress before completion';
  end if;

  task_price := coalesce(target.price, 0);

  select * into customer_wallet from public.wallets where user_id = target.customer_id for update;
  if not found then
    insert into public.wallets (user_id) values (target.customer_id)
    returning * into customer_wallet;
  end if;

  select * into runner_wallet from public.wallets where user_id = target.assigned_runner_id for update;
  if not found then
    insert into public.wallets (user_id) values (target.assigned_runner_id)
    returning * into runner_wallet;
  end if;

  if customer_wallet.balance < task_price then
    raise exception 'Customer wallet has insufficient balance';
  end if;

  update public.wallets set balance = balance - task_price where id = customer_wallet.id;
  update public.wallets set balance = balance + task_price where id = runner_wallet.id;

  insert into public.transactions (wallet_id, type, amount, description, related_errand_id)
  values
    (customer_wallet.id, 'payment', -task_price, 'Payment for: ' || target.title, target.id),
    (runner_wallet.id, 'earning', task_price, 'Earning from: ' || target.title, target.id);

  update public.errands
  set status = 'completed', completed_at = now()
  where id = target.id
  returning * into target;

  insert into public.task_tracking (
    errand_id,
    phase,
    delivered_at,
    eta_minutes,
    distance_to_next_km,
    updated_at
  )
  values (target.id, 'delivered', now(), 0, 0, now())
  on conflict (errand_id) do update
  set
    phase = 'delivered',
    delivered_at = coalesce(public.task_tracking.delivered_at, now()),
    eta_minutes = 0,
    distance_to_next_km = 0,
    updated_at = now();

  return target;
end;
$$;

-- Storage Bucket Setup for ID Verifications
insert into storage.buckets (id, name, public)
values ('verifications', 'verifications', true)
on conflict (id) do nothing;

-- Drop existing policies if they exist to avoid duplication
drop policy if exists "Allow authenticated uploads to verifications" on storage.objects;
drop policy if exists "Allow users and admins to view verifications" on storage.objects;


-- Create policy to allow authenticated users to upload their verification IDs
create policy "Allow authenticated uploads to verifications" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'verifications'
  );

-- Create policy to allow users to view their own IDs and admins to view all IDs
create policy "Allow users and admins to view verifications" on storage.objects
  for select to authenticated using (
    bucket_id = 'verifications'
    and (
      (storage.foldername(name))[1] = auth.uid()::text
      or exists (select 1 from public.profiles where id = auth.uid() and is_admin)
    )
  );
